#!/bin/sh
module="aesdchar"
device="aesdchar"
mode="664"
kernel_ver="$(uname -r)"

# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

if [ -e /lib/modules/$kernel_ver/extra/$module.ko ]; then
    echo "Loading /lib/modules/$kernel_ver/extra/$module.ko"
    insmod /lib/modules/$kernel_ver/extra/$module.ko $* || exit 1
else
    echo "Module not found in /lib/modules/$kernel_ver/extra/, attempting modprobe"
    modprobe $module || exit 1
fi

major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
rm -f /dev/${device}
mknod /dev/${device} c $major 0
chgrp $group /dev/${device}
chmod $mode /dev/${device}
